### ISSUE TITLE
defaults.exclude_tags

### ISSUE THREAD

**Issue by jeremyschulman** [netpaca/netpaca#2]
Add configuration in the `[defaults]` section of the config called `exclude_tags` so that the User can identify the columns in the inventory file that they do not want automatically converted to metric tags.  For example if the inventory file contains columns for username and password:

````toml
[defaults]
   exclude_tags = ['username', 'password']
````
